### ISSUE TITLE
feed dependency

### ISSUE THREAD

**Issue by dzhus** [psibi/download#14]
Hi,

It looks like the latest version of `download` currently published on Hackage has a dependency on [`feed`][feed] package without an upper bound specified.

A new version of `feed` will be released soon, incorporating [non-backwards compatible changes][feed-pr] to `feed` interface (`String` was replaced with `Text` throughout and `xml-types` types were adopted). Changes are largely mechanical but you'll probably want to ensure that future version of `download` can build with newer `feed`.

To prevent breakage, you may want to release a new version of `download` with an upper bound specified now, then push a version compatible with `feed-1.0` after that comes out later.

Use the tip of the `feed` PR to test your package against: https://github.com/dzhus/feed/commit/259bab0. Please report any issues to the aforementioned [PR thread][feed-pr].

[feed]: http://hackage.haskell.org/package/feed
[feed-pr]: https://github.com/bergmark/feed/pull/20

**Comment by psibi** [comment]
> String was replaced with Text throughout

Are you sure ?

`download` just uses `parseFeedString` function and I'm sure it's present in the newer release of the library: https://www.stackage.org/haddock/nightly-2017-09-07/feed-1.0.0.0/Text-Feed-Import.html#v:parseFeedString

So, I guess I'm safe ?

**Comment by dzhus** [comment]
@psibi If so then yes, you're safe - that function should still work
