### ISSUE TITLE
Compilation error with libio.h

### ISSUE THREAD

**Issue by muesli4** [psibi/download#16]
I don't know what the file is for but when I try to build it I get errors by these lines:

https://github.com/psibi/download/blob/98c694c8bcfaff6801158774d1dff80ff3984dee/cbits/ftp.c#L67
https://github.com/psibi/download/blob/98c694c8bcfaff6801158774d1dff80ff3984dee/cbits/http.c#L71

Simply removing both lines leads to successful compilation but then it throws and I get:

    > import Network.Download
    > openURI "http://haskell.org"
    Left "Failed to connect: Success"

I'm using:
* Archlinux (Linux 4.18.10-arch1-1-ARCH)
* GHC 8.4.3

Let me know if you need something else.

**Comment by Murzinio** [comment]
Tried it on Arch and I get the same error too. After some googling it seems it's supposed to be a part of the GNU C library, but it's not there even though glibc is installed. (Arch has it in core packages) Looking at the C headers reference https://en.cppreference.com/w/c/header you can see it's not really guaranteed to be part of the C stdlib so that's where the problem comes from I guess.

**Comment by muesli4** [comment]
@Murzinio It worked before. I guess it's not really related to Archlinux in particular. It's not even listed there and in some code I found it says that it should only be included by glibc itself. I'm interested what it's used for but couldn't figure it out without wasting a lot of time.

**Comment by erikd** [comment]
The `<libio.h>` header used to be provided by the kernel, but has since [been deprecated](https://patchwork.kernel.org/patch/10158257/).

The deprecation warning suggests using `<stdio.h>` instead.

**Comment by muesli4** [comment]
Compiles but doesn't work:
```
> openURI "http://haskell.org"
Left "Failed to connect: Success"
```

**Comment by erikd** [comment]
@muesli4 I don't think that test failure is due to the my fix, but rather due to flakiness of the test.

**Comment by psibi** [comment]
A new version has been released in Hackage. Thanks @erikd for the patch.

**Comment by muesli4** [comment]
Should I open another issue? The compilation error is gone but it's still not working properly.

**Comment by psibi** [comment]
Yeah, please open another issue. Thanks.
