### ISSUE TITLE
Build fails in OSX

### ISSUE THREAD

**Issue by dareTake** [psibi/download#4]
Trying to `stack build` using download as a dependency fails in OSX 10.11 . 

Error message: 
```
fatal error: 'libio.h' file not found
#include <libio.h>
         ^
1 error generated.
 `gcc' failed in phase `C Compiler'. (Exit code: 1)
```

**Comment by psibi** [comment]
Is `glibc` libraries in path ? I don't have a OSX to test it. Also, Is `cabal install download` working or is this just repeatable with `stack` ?

**Comment by psibi** [comment]
Error reproduced in OSX Travis build: https://travis-ci.org/psibi/download/jobs/145333462#L325

**Comment by crowder** [comment]
I am currently failing on "cabal install download" with this exact error, in answer to your question from Jun 12. What is the fix?

**Comment by crowder** [comment]
FWIW, as an added detail, my cabal install is using clang (not gcc) as the C-compiler.

**Comment by psibi** [comment]
Yeah, it doesn't work on Mac right now as I don't have the machine. I would by happy to receive a patch fixing it.

**Comment by crowder** [comment]
So basically it looks like Mac OS X doesn't have fopencookie(), but it does have funopen().

Here's a hack I did that makes it at least succeed "install":

```
Brians-MBP:ImplicitCAD crowder$ diff -r download-0.3.2.4-fixed/ download-0.3.2.4
diff -r download-0.3.2.4-fixed/cbits/ftp.c download-0.3.2.4/cbits/ftp.c
66c66
< //#include <libio.h>
---
> #include <libio.h>
585c585,590
<         f = funopen(io, _ftp_readfn, _ftp_writefn, _ftp_seekfn, _ftp_closefn);
---
>     cookie_io_functions_t cookies;
>     cookies.read = (cookie_read_function_t *)_ftp_readfn;
>     cookies.write = (cookie_write_function_t *)_ftp_writefn;
>     cookies.seek = (cookie_seek_function_t *)_ftp_seekfn;
>     cookies.close = (cookie_close_function_t *)_ftp_closefn;
>     f = fopencookie(io, "rw", cookies);
diff -r download-0.3.2.4-fixed/cbits/http.c download-0.3.2.4/cbits/http.c
69a70
> #include <libio.h>
323c324,329
<         f = funopen(io, _http_readfn, _http_writefn, NULL, _http_closefn);
---
>     cookie_io_functions_t cookie;
>     cookie.read = (cookie_read_function_t *)_http_readfn;
>     cookie.write = (cookie_write_function_t *)_http_writefn;
>     cookie.seek = (cookie_seek_function_t *)NULL;
>     cookie.close = (cookie_close_function_t *)_http_closefn;
>     f = fopencookie(io, "rw", cookie);
```

I have no idea how to polish this for distribution across different configurable platforms, however.

**Comment by crowder** [comment]
Errr, whoops. I reversed that patch. If you want it the other way 'round, I can do that.

**Comment by crowder** [comment]
Additional info: libio.h is not extant on my machine at all, anywhere, as far as I can tell.

**Comment by psibi** [comment]
Yes, I guess that. Probably we need some CPP conditional for including something else for Mac systems which supply the relevant functions. Unfortunately, I don't have much expertise with the mac System API's. But I would love if someone fixes this problem. :)

**Comment by crowder** [comment]
Well, I'm happy to try out anything you come up with to see if it builds on my machine, hopefully the patch above is a good start.

**Comment by psibi** [comment]
@crowder Can you send a pull request ? I will see if it passes travis test for mac.

**Comment by crowder** [comment]
Submitted a PR, and on the day I submitted, they all passed, I *thought*. Now seeing in the PR they show failed (cancelled, I think?). Is there a way to rerun?
