### ISSUE TITLE
Linker reports “unknown symbol `stat64'” when trying to use the library

### ISSUE THREAD

**Issue by leftaroundabout** [psibi/download#5]
This [seems to be a really old problem](https://mail.haskell.org/pipermail/haskell-cafe/2011-January/088597.html), but it still happens: when I try to use `download` (on Ubuntu-14.04, with GHC-7.10), I get the ridiculous error

    ~/.cabal/lib/x86_64-linux-ghc-7.10.2/download-0.3.2.4-GglUNCzzEM5GEneu9jc8yk/libHSdownload-0.3.2.4-GglUNCzzEM5GEneu9jc8yk.a: unknown symbol `stat64'

**Comment by psibi** [comment]
Can you add more details ? How did you try to use the library - via Ghci or do you have any sample code ?

A related thread: https://ghc.haskell.org/trac/ghc/ticket/7072

I'm also currently on Ubuntu 14.04 and my [tests](https://github.com/psibi/download/blob/master/Spec.hs) are working fine in my system.

**Comment by leftaroundabout** [comment]
Aha, interesting, turns out it only happens in IHaskell.

https://gist.github.com/leftaroundabout/b31ab94a55649ca806429f490352e992

**Comment by psibi** [comment]
I'm closing this issue. Please re-open if required.
